### ISSUE TITLE
Terminate Markov evaluator

### ISSUE THREAD

**Issue by RasmusRendal** [RasmusRendal/crnsimul#56]
At the moment, the only way the Markov evaluator will mark itself as "finished" is if there are no more reactions possible in the current state. However, most useful CRNs end up in some sort of equilibrium, which the Markov evaluator will just sit on infinitely. 

So we either neet some sort of way to detect that we've reached an equilibrium (might be the halting problem in disguise), or just set a cap on the iterations we're willing to perform.

**Comment by adramaxxx** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [chemilang](https://trello.com/c/Hra6tM3R/74-chemilang)
